##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="traefik" \
    CONTECO_NAME="base" \
    CONTECO_TAG="v2.3.1" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="traefik" \
      io.vcweb.name="base" \
      io.vcweb.tag="v2.3.1" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="traefik.base - Conteco" \
      io.vcweb.description="Traefik Base image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.traefik.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
