##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.traefik:v2.1 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/conteco/bin/traefik/base/entrypoint"
COPY ./conteco/configs/etc/traefik/traefik.yml /etc/traefik/traefik.yml
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="traefik" \
    CONTECO_NAME="base" \
    CONTECO_TAG="v2.3.1" \
    CONTECO_BASE="external.traefik:v2.1" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="traefik" \
      io.vcweb.name="base" \
      io.vcweb.tag="v2.3.1" \
      io.vcweb.base="external.traefik:v2.1" \
      io.vcweb.build="image-base" \
      io.vcweb.label="traefik.base - Conteco" \
      io.vcweb.description="Traefik Base image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.traefik.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
