#!/usr/bin/env bash

export CONTECO_LABEL="traefik.base - Conteco"
export CONTECO_DESCRIPTION="Traefik Base image, using default configuration."

export CONTECO_TYPE="traefik"
export CONTECO_NAME="base"
export CONTECO_TAG="v2.3.1"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="traefik:v2.3.1"
