#!/usr/bin/env bash

export CONTECO_LABEL="Conteco Traefik base"
export CONTECO_DESCRIPTION="The Traefik base image."

export CONTECO_TYPE="traefik"
export CONTECO_NAME="base"
export CONTECO_TAG="v2.1"

export CONTECO_BASE="external.traefik:v2.1"
export CONTECO_BUILD="image-base"
