## traefik.yml
entrypoints:
  conteco:
    address: ":80"
  traefik:
    address: ":8080"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    watch: true
    swarmMode: true
    exposedByDefault: false
    network: ${CONTECO_ECOSYSTEM_RUNTIME}_overlay

# API and dashboard configuration
api:
  insecure: true
ping:
  entrypoint: traefik
metrics:
  prometheus:
    entryPoint: traefik
    buckets: [0.1,0.3,1.2,5.0]
