## traefik.yml
entrypoints:
  conteco:
    address: ":80"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    watch: true
    swarmMode: true
    exposedByDefault: false
    network: conteco_overlay

# API and dashboard configuration
api:
  insecure: true
